
name: CI
#当main分支push时触发，可以限定分支或标签。
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: echo 1
